apiVersion: v2
name: hashr
description: A Helm chart for HashR Kubernetes deployments.
version: 0.1.0
type: application
keywords:
- hashr
- dfir
- analysis
- security
home: "https://github.com/google/hashr"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  version: 14.3.3
  repository: https://charts.bitnami.com/bitnami
maintainers:
  - name: Open Source DFIR
    email: osdfir-maintainers@googlegroups.com
    url: https://github.com/google/osdfir-infrastructure
sources:
- https://github.com/google/hashr
- https://github.com/google/osdfir-infrastructure
appVersion: "latest"
annotations:
  category: Security
  licenses: Apache-2.0
