{{- if .Values.agents.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yeti-agents
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: agents
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: agents
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: agents
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      containers:
        - name: agents
          image: "{{ .Values.agents.image.repository }}:{{ .Values.agents.image.tag }}"
          imagePullPolicy: {{ .Values.agents.image.pullPolicy | default .Values.config.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            seccompProfile:
              type: RuntimeDefault
          env:
          {{- include "yeti.envs" . | nindent 12 }}
          ports:
            - containerPort: 8888
              name: http
          resources:
            {{- toYaml .Values.agents.resources | nindent 12 }}
      {{- with .Values.agents.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
