apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yeti.fullname" . }}-nginx-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
data:
  default.conf: |
    server {

        root /www;

        location /api/v2 {
            proxy_pass http://{{ include "yeti.fullname" . }}-api:8000;
        }
        
        location ~(^/docs|^/openapi.json) {
            proxy_pass http://{{ include "yeti.fullname" . }}-api:8000;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }