{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-yeti-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  {{ $secretName := printf "%s-yeti-secret" (.Release.Name) }}
  yeti-user: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "yeti-user" }}
  yeti-arangodb: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "yeti-arangodb" }}
  yeti-secret: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "yeti-secret" }}
  {{- else }}
  yeti-user: {{ randAlphaNum 32 | b64enc | quote }}
  yeti-arangodb: {{ randAlphaNum 16 | b64enc | quote }}
  yeti-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}