apiVersion: v1
kind: Secret
metadata:
  name: sec-grr-server-local
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  server.local.yaml: |
    Database.implementation: MysqlDB
    {{- if (and .Values.grr.blobstore .Values.grr.blobstore.bucket) }}
    Blobstore.implementation: GCSBlobStore
    Blobstore.gcs.project: {{ .Values.global.projectId }}
    Blobstore.gcs.bucket: {{ .Values.grr.blobstore.bucket }}
    {{- else }}
    Blobstore.implementation: DbBlobStore
    {{- end }}
    Mysql.host: {{ .Values.grr.mysqlDb.address }}
    Mysql.port: {{ .Values.grr.mysqlDb.port }}
    Mysql.database: {{ .Values.grr.mysqlDb.name }}
    Mysql.username: {{ .Values.grr.mysqlDb.userName }}
    Mysql.password: {{ .Values.grr.mysqlDb.userPassword }}
    Mysql.flow_processing_threads_max: 20
    AdminUI.csrf_secret_key: KPK,_0a_xY&DTeiaokEdsH1uXGobNIhfrr67BTSLlPPv64_UE0nyn8QsD6
    AdminUI.url: http://localhost:{{ .Values.grr.admin.listenPort }}
    AdminUI.bind: 0.0.0.0
    AdminUI.use_precompiled_js: true
    API.DefaultRouter: ApiCallRouterWithoutChecks

    Logging.domain: localhost
    Logging.verbose: true
    Logging.engines: file,stderr
    Logging.path: /grr
    Logging.filename: /grr/grr-server.log
    Monitoring.alert_email: grr-monitoring@localhost
    Monitoring.emergency_access_email: grr-emergency@localhost
    Monitoring.http_address: 0.0.0.0
    Monitoring.http_port: {{ .Values.prometheus.metricsPort }}

    Server.initialized: true
    Server.fleetspeak_enabled: true
    Server.fleetspeak_server: svc-fleetspeak-admin:{{ .Values.fleetspeak.admin.listenPort }}
    Server.fleetspeak_message_listen_address: 0.0.0.0:{{ .Values.grr.frontend.listenPort }}
    {{- if (and .Values.grr.pubsub .Values.grr.pubsub.topic) }}
    Server.fleetspeak_cps_enabled: true
    Server.fleetspeak_cps_project: {{ .Values.grr.pubsub.project }}
    Server.fleetspeak_cps_subscription: {{ .Values.grr.pubsub.subscription }}
    Server.fleetspeak_cps_concurrency: 10
    {{- end }}

    # Configuration for repacking client templates:
    PrivateKeys.executable_signing_private_key: "EXE_SIGN_PRIVATE_KEY"
    Client.executable_signing_public_key: "EXE_SIGN_PUBLIC_KEY"

    Client.fleetspeak_enabled: true
    ClientBuilder.fleetspeak_bundled: true
    ClientBuilder.template_dir: /client_templates
    ClientBuilder.executables_dir: /client_installers

    Target:Linux:
      ClientBuilder.fleetspeak_client_config: /config/config.textproto
    Target:Windows:
      ClientBuilder.fleetspeak_client_config: /config/config.textproto
    Target:Darwin:
      ClientBuilder.fleetspeak_client_config: /config/config.textproto
