apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-yeti-arangodb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8529 
      protocol: TCP
  selector:
    app.kubernetes.io/component: arangodb
    {{- include "yeti.selectorLabels" . | nindent 4 }}