{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "yeti.fullname" . }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingressClassName: {{ .Values.ingress.className }}
    {{- if .Values.ingress.gcp.managedCertificates }}
    networking.gke.io/managed-certificates: {{ include "yeti.fullname" . }}-managed-ssl
    {{- end }}
    {{- if (eq .Values.ingress.className "gce") }}
    {{- if .Values.ingress.gcp.staticIPName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gcp.staticIPName }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "yeti.fullname" . }}-frontend-config
    {{- else }}
    {{- fail "A valied .Values.ingress.gcp.staticIPName entry is required when using the GCE Ingress" }}
    {{- end }}
    {{- end }}
spec:
  rules:
    - host: {{ required "A valid .Values.ingress.host entry is required!" .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "yeti.fullname" . }}
                port:
                  number: {{ include "yeti.service.port" . }}
  defaultBackend:
    service:
      name: {{ include "yeti.fullname" . }} # Name of the Service targeted by the Ingress
      port:
        number: {{ include "yeti.service.port" . }} # Should match the port used by the Service
{{- end }}
{{- if and .Values.ingress.enabled .Values.ingress.gcp.staticIPV6Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "yeti.fullname" . }}-ingress-ipv6
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingressClassName: {{ .Values.ingress.className }}
    {{- if .Values.ingress.gcp.managedCertificates }}
    networking.gke.io/managed-certificates: {{ include "yeti.fullname" . }}-managed-ssl
    {{- end }}
    {{- if (eq .Values.ingress.className "gce") }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gcp.staticIPV6Name }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "yeti.fullname" . }}-frontend-config
    {{- end }}
spec:
  rules:
    - host: {{ required "A valid .Values.ingress.host entry is required!" .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "yeti.fullname" . }}
                port:
                  number: {{ include "yeti.service.port" . }}
  defaultBackend:
    service:
      name: {{ include "yeti.fullname" . }} # Name of the Service targeted by the Ingress
      port:
        number: {{ include "yeti.service.port" . }} # Should match the port used by the Service
{{- end }}