apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: 
    helm.sh/resource-policy: keep
  name: {{ .Release.Name }}-arangodbvolume-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "yeti.storage.class" . | nindent 2 }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}