apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "yeti.fullname" . }}-tasks
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: tasks
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: tasks
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Have Deployment restart after each upgrade
        roll: {{ randAlphaNum 5 | quote }}
        {{- if .Values.metrics.enabled }} 
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        app.kubernetes.io/component: tasks
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "yeti.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.tasks.podSecurityContext | nindent 8 }}
      containers:
        - name: tasks
          securityContext:
              {{- toYaml .Values.tasks.securityContext | nindent 12 }}
          image: "{{ .Values.tasks.image.repository }}:{{ .Values.tasks.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.tasks.image.pullPolicy }}
          command: ["sh", "-c", "/docker-entrypoint.sh tasks"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
                  apiVersion: v1
            - name: YETI_REDIS_HOST
              value: {{ include "yeti.redis.url" . }}
            - name: YETI_REDIS_PORT
              value: "{{ .Values.redis.master.service.ports.redis }}"
            - name: YETI_REDIS_DATABASE
              value: "0"
            - name: YETI_ARANGODB_HOST
              value: {{ include "yeti.fullname" . }}-arangodb
            - name: YETI_ARANGODB_PORT
              value: "8529"
            - name: YETI_ARANGODB_DATABASE
              value: yeti
            - name: YETI_ARANGODB_USERNAME
              value: root
            - name: YETI_AUTH_SECRET_KEY
              value: SECRET
            - name: YETI_AUTH_ALGORITHM
              value: HS256
            - name: YETI_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: YETI_AUTH_ENABLED
              value: "False"
          volumeMounts:
            - mountPath: /mnt/yeti
              name: yetivolume
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
            {{- end }}
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.tasks.resources | nindent 12 }}
      volumes:
        - name: yetivolume
          persistentVolumeClaim:
            claimName: {{ include "yeti.pvc.name"  . }}
            readOnly: false
      {{- with .Values.tasks.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tasks.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tasks.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
