apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-yeti-tasks
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: tasks
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: tasks
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tasks
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: tasks
          image: "{{ .Values.tasks.image.repository }}:{{ .Values.tasks.image.tag }}"
          imagePullPolicy: {{ .Values.tasks.image.pullPolicy }}
          command: ["sh", "-c", "/docker-entrypoint.sh tasks"]
          env:
          {{- include "yeti.envs" . | nindent 12 }}
          resources:
            {{- toYaml .Values.tasks.resources | nindent 12 }}
      {{- with .Values.tasks.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}