remote: origin
target-branch: main
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - opensearch=https://opensearch-project.github.io/helm-charts
chart-dirs:
  - charts
check-version-increment: false
validate-maintainers: false
helm-extra-args: --timeout 600s