apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yeti-redis-pdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: yeti