apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-openrelik-prometheus
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: prometheus
    {{- include "openrelik.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      {{- include "openrelik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus
        {{- include "openrelik.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
              name: prometheus-config
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ .Release.Name }}-openrelik-prometheus-configmap
            defaultMode: 420