apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openrelik-prometheus-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      external_labels:
        monitor: "openrelik"
    scrape_configs:
      - job_name: "celery"
        static_configs:
          - targets: ["{{ .Release.Name }}-openrelik-metrics:8080"]
