apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openrelik-prometheus
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/component: prometheus
    {{- include "openrelik.selectorLabels" . | nindent 4 }}