apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openrelik-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
  {{- if (eq .Values.global.ingress.className "gce") }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8710":"{{ .Release.Name }}-openrelik-api-backend-config"}}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8710
      protocol: TCP
      targetPort: 8710
  selector:
    app.kubernetes.io/component: api
    {{- include "openrelik.selectorLabels" . | nindent 4 }}