apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openrelik
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8711
      protocol: TCP
      targetPort: 8711
  selector:
    app.kubernetes.io/component: frontend
    {{- include "openrelik.selectorLabels" . | nindent 4 }}