{{- if and (.Values.config.oidc.authenticatedEmailsFile.enabled) (not .Values.config.oidc.authenticatedEmailsFile.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-openrelik-access-list
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openrelik.labels" . | nindent 4 }}
type: Opaque
data:
  authenticated-emails-list: {{ .Values.config.oidc.authenticatedEmailsFile.content | b64enc | quote }}
{{- end -}}