apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hashr-postgres
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hashr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/component: postgres
    {{- include "hashr.selectorLabels" . | nindent 4 }}
