{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: turbinia-metrics-servicemonitor
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: http-metrics
{{ end -}}