apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-timesketch-postgres-networkpolicy
  labels:
    app.kubernetes.io/component: postgres
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 5432
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: postgres
  policyTypes:
  - Ingress
  - Egress