apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-hashr-data-manager
spec:
  containers:
  - name: hashr-data-manager
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "while true; do sleep 1800; done;"]
    volumeMounts:
    - name: hashrvolume
      mountPath: /mnt/hashrvolume/data
  restartPolicy: Always
  volumes:
  - name: hashrvolume
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-hashrvolume-claim
      readOnly: false
