apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hashr-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hashr.labels" . | nindent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  {{ $secretName := printf "%s-hashr-secret" (.Release.Name) }}
  postgres-user: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName).data "postgres-user" }}
  {{- else }}
  postgres-user: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
