{{- if and .Values.ingress.enabled .Values.ingress.certManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "yeti.fullname" . }}-letsencrypt-production
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ include "yeti.fullname" . }}-letsencrypt-production
    solvers:
    - http01:
        ingress:
          name: {{ include "yeti.fullname" . }}-ingress
{{- end }}