PrivateKeys.executable_signing_private_key: "EXE_SIGN_PRIVATE_KEY"
Client.executable_signing_public_key: "EXE_SIGN_PUBLIC_KEY"
# Configuration for repacking client templates:
Client.fleetspeak_enabled: true
ClientBuilder.fleetspeak_bundled: true
ClientBuilder.template_dir: /client_templates
ClientBuilder.executables_dir: /client_installers

Target:Linux:
  ClientBuilder.fleetspeak_client_config: /config/config.textproto
Target:Windows:
  ClientBuilder.fleetspeak_client_config: /config/config.textproto
Target:Darwin:
  ClientBuilder.fleetspeak_client_config: /config/config.textproto
