{{- if and .Values.global.ingress.enabled .Values.global.ingress.certManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-osdfir-letsencrypt-production
  labels:
    {{- include "osdfir.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Name }}-osdfir-letsencrypt-production
    solvers:
    - http01:
        ingress:
          name: {{ .Release.Name }}-osdfir-ingress
{{- end }}