{{- if and (.Values.ingress.enabled) (.Values.ingress.gcp.managedCertificates) }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "timesketch.fullname" . }}-managed-ssl
  namespace: {{ .Release.Namespace | quote }}
spec:
  domains: 
    - {{ required "A valid .Values.ingress.host entry is required!" .Values.ingress.host }}
{{- end }}