{{- if and .Values.chromadb .Values.chromadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-yeti-chromadb
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: chromadb
    {{- include "yeti.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-yeti-chromadb
  selector:
    matchLabels:
      app.kubernetes.io/component: chromadb
      {{- include "yeti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/component: chromadb
        {{- include "yeti.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chromadb
          image: "{{ .Values.chromadb.image.repository }}:{{ .Values.chromadb.image.tag }}"
          imagePullPolicy: {{ .Values.chromadb.image.pullPolicy }}
          env:
            - name: ANONYMIZED_TELEMETRY
              value: "FALSE"
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /api/v2/heartbeat
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v2/heartbeat
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            {{- toYaml .Values.chromadb.resources | nindent 12 }}
      {{- with .Values.chromadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.chromadb.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.chromadb.persistence.size | quote }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
{{- end }}
