apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-yeti-nginx-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "yeti.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 9000;
        listen [::]:9000;
        root /www;

        location /api/v2 {
            proxy_pass http://{{ .Release.Name }}-yeti-api:8000;
        }
        
        location ~(^/docs|^/openapi.json) {
            proxy_pass http://{{ .Release.Name }}-yeti-api:8000;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }