{{- if and .Values.ingress.enabled (or .Values.ingress.selfSigned .Values.ingress.certManager) }}
{{- $secretName := printf "%s-tls" (include "timesketch.fullname" .) }}
{{- $ca := genCA "timesketch-ca" 365 }}
{{- $cert := genSignedCert "timesketch-apps" nil (list .Values.ingress.host) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timesketch.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}