{{- if or (.Values.ingress.enabled) (.Values.global.ingress.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timesketch.fullname" . }}-nginx-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        listen [::]:80;
        client_max_body_size 0m;
        location / {
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            proxy_pass http://{{ include "timesketch.fullname" . }}:5000/;
            proxy_read_timeout 120s;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /healthz {
            return 200;
        }
    }
{{- end }}