apiVersion: v1
kind: Service
metadata:
  name: {{ include "timesketch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "timesketch.service.port" . }}
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.selectorLabels" . | nindent 4 }}