apiVersion: v1
kind: Service
metadata:
  name: {{ include "timesketch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
  {{- if and (.Values.ingress.enabled) ( eq .Values.ingress.className "gce") }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"5000":"{{ include "timesketch.fullname" . }}-backend-config"}}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "timesketch.service.port" . }}
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.selectorLabels" . | nindent 4 }}