apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "timesketch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: frontend
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "timesketch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Restart pod if values.yaml parameters that affect the config were changed
        checksum/config: {{  include (print $.Template.BasePath "/init-configmap.yaml") . | sha256sum }}
        {{- if .Values.metrics.enabled }} 
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        app.kubernetes.io/component: frontend
        {{- include "timesketch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "timesketch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      initContainers:
      {{- include "timesketch.initContainer" . | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
              {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "./docker-entrypoint.sh timesketch-web"]
          {{- if .Values.config.createUser }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "tsctl create-user timesketch --password $TIMESKETCH_USER"]
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
                  apiVersion: v1
            {{- if .Values.config.createUser }}
            - name: TIMESKETCH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "timesketch.fullname" . }}-secret 
                  key: timesketch-user
            {{- end }}
          volumeMounts:
            - mountPath: {{ (include "timesketch.uploadPath" .) | quote }}
              name: timesketchvolume
              subPath: uploads
            - mountPath: /var/log/timesketch
              name: timesketchvolume
              subPathExpr: logs/$(POD_NAME)
            - mountPath: /etc/timesketch
              name: timesketch-configs
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
            {{- end }}
            - containerPort: 5000
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: timesketchvolume
          persistentVolumeClaim:
            claimName: {{ include "timesketch.pvc.name"  . }}
            readOnly: false
        - name: init-timesketch
          configMap:
            name: {{ include "timesketch.fullname" . }}-init-configmap
            defaultMode: 0744
        - name: timesketch-configs
          emptyDir: {}
        {{- if .Values.config.existingConfigMap }}
        - name: uploaded-configs
          configMap:
            name: {{ .Values.config.existingConfigMap }}
        {{- end }}
        {{- if .Values.config.oidc.authenticatedEmailsFile.enabled }}
        - name: authenticated-emails
          secret:
            items:
            - key: authenticated-emails-list
              path: authenticated-emails-list
            secretName: {{ include "timesketch.oidc.authenticatedemails" . }}
        {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
