apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grr-frontend
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    app: grr-frontend
spec:
  replicas: {{ .Values.grr.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grr-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grr-frontend
        prometheus: grr-frontend
    spec:
      serviceAccountName: {{ .Release.Name }}-grr-sa
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nodepool
                operator: In
                values:
                - grr
      initContainers:
      - name: init-fleetspeak-health-check
        image: bitnami/git
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          until [ "$(curl -s -w '%{http_code}' -o /dev/null http://{{ .Release.Name }}-grr-fleetspeak-admin:{{ .Values.fleetspeak.admin.healthCheckPort }})" -eq 200 ]
          do
            echo "Waiting for Fleetspeak Admin to be ready";
            sleep 5;
          done
          echo "Fleetspeak Admin health check is ready"
      - name: init-exe-sign
        image: bitnami/git
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          cp /sign/keys/*.pem /grr/exe/sign/keys/
          if [ -e /sign/keys/exe-sign.crt ]
          then
            echo "Extracting public key from certificate..."
            openssl x509 -in /sign/keys/exe-sign.crt -pubkey -noout > /grr/exe/sign/keys/exe-sign-public-key.pem
          fi
        volumeMounts:
        - name: grr-exe-sign-keys-volume
          mountPath: /grr/exe/sign/keys
        - name: grr-exe-sign-keys-secret
          mountPath: /sign/keys
      containers:
      - name: grr-frontend
        image: {{ .Values.grr.frontend.image }}
        {{- if .Values.global.useResourceRequests }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        {{- end }}
        ports:
        - containerPort: {{ .Values.grr.frontend.listenPort }}
          name: frontend
        - containerPort: {{ .Values.prometheus.metricsPort }}
          name: metrics
        args: ["-component", "frontend", "-config", "/usr/src/grr/grr/core/install_data/etc/server.local.yaml", "--logtostderr"]
        volumeMounts:
        - name: grr-frontend-config
          mountPath: /usr/src/grr/grr/core/install_data/etc/server.local.yaml
          subPath: server.local.yaml
        - name: grr-exe-sign-keys-volume
          readOnly: true
          mountPath: "/grr/exe/sign/keys"
      volumes:
      - name: grr-frontend-config
        secret:
          secretName: {{ .Release.Name }}-grr-server-local
          items:
          - key: server.local.yaml
            path: server.local.yaml
      - name: grr-exe-sign-keys-secret
        secret:
          secretName: {{ .Release.Name }}-grr-executable-signing-keys
      - name: grr-exe-sign-keys-volume
        emptyDir:
          sizeLimit: 5Mi
