{{- if and (.Values.ingress.enabled) (eq .Values.ingress.className "gce") }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}-timesketch-frontend-config
  namespace: {{ .Release.Namespace | quote }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}