{{- if .Values.config.enableServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timesketch
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
{{- end }}