{{- if or (and (.Values.ingress.enabled) (eq .Values.ingress.className "gce")) (and (.Values.global.ingress.enabled) (eq .Values.global.ingress.className "gce")) }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "yeti.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace | quote }}
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /login/
    port: 80
{{- end }}