apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-timesketch-nginx-networkpolicy
  labels:
    app.kubernetes.io/component: nginx
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: nginx
  policyTypes:
  - Ingress
  - Egress