apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-timesketch-nginx-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 8080;
        listen [::]:8080;
        client_max_body_size 0m;
        location / {
            # --- Robust Memory Buffering Configurations ---
            proxy_buffering {{ .Values.nginx.config.proxyBuffering | default "on" }};
            proxy_buffer_size {{ .Values.nginx.config.proxyBufferSize | default "128k" }};
            proxy_buffers {{ .Values.nginx.config.proxyBuffers | default "4 256k" }};
            proxy_busy_buffers_size {{ .Values.nginx.config.proxyBusyBuffersSize | default "256k" }};

            # Safety gate to prevent GKE Ephemeral-Storage pod eviction (DiskPressure)
            proxy_max_temp_file_size {{ .Values.nginx.config.proxyMaxTempFileSize | default "512M" }};

            proxy_read_timeout {{ .Values.config.nginxReadTimeout }}s;
            proxy_pass http://{{ .Release.Name }}-timesketch:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        {{- if .Values.opensearch.dashboard.ingress }}
        location /opensearch {
            proxy_pass http://{{ .Release.Name }}-opensearch-dashboard:5601;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        {{- end }}
        location /healthz {
            return 200;
        }
        location /v3 {
            # --- Robust Memory Buffering Configurations ---
            proxy_buffering {{ .Values.nginx.config.proxyBuffering | default "on" }};
            proxy_buffer_size {{ .Values.nginx.config.proxyBufferSize | default "128k" }};
            proxy_buffers {{ .Values.nginx.config.proxyBuffers | default "4 256k" }};
            proxy_busy_buffers_size {{ .Values.nginx.config.proxyBusyBuffersSize | default "256k" }};

            # Safety gate to prevent GKE Ephemeral-Storage pod eviction (DiskPressure)
            proxy_max_temp_file_size {{ .Values.nginx.config.proxyMaxTempFileSize | default "512M" }};

            proxy_read_timeout {{ .Values.config.nginxReadTimeout }}s;
            proxy_pass http://{{ .Release.Name }}-timesketch-v3:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
