apiVersion: v1
kind: Secret
metadata:
  name: sec-fleetspeak-admin-components
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  admin.components.textproto: |
    mysql_data_source_name: "{{ .Values.fleetspeak.mysqlDb.userName }}:{{ .Values.fleetspeak.mysqlDb.userPassword }}@tcp({{ .Values.fleetspeak.mysqlDb.address }}:{{ .Values.fleetspeak.mysqlDb.port }})/{{ .Values.fleetspeak.mysqlDb.name }}"
    admin_config: <
      listen_address: "0.0.0.0:{{ .Values.fleetspeak.admin.listenPort }}"
    >
    notification_use_http_notifier: true
    stats_config: <
      address: "0.0.0.0:{{ .Values.prometheus.metricsPort }}"
    >
