apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-grr-frontend
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    app: grr-frontend
spec:
  replicas: {{ .Values.grr.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grr-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grr-frontend
        prometheus: grr-frontend
    spec:
      serviceAccountName: grr-sa
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nodepool
                operator: In
                values:
                - grr
      containers:
      - name: grr-frontend
        image: {{ .Values.grr.frontend.image }}
        {{- if .Values.global.useResourceRequests }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        {{- end }}
        ports:
        - containerPort: {{ .Values.grr.frontend.listenPort }}
          name: frontend
        - containerPort: {{ .Values.prometheus.metricsPort }}
          name: metrics
        args: ["-component", "frontend", "-config", "/usr/src/grr/grr/core/install_data/etc/server.local.yaml", "--logtostderr"]
        volumeMounts:
        - name: grr-frontend-config
          mountPath: /usr/src/grr/grr/core/install_data/etc/server.local.yaml
          subPath: server.local.yaml
        - name: grr-exe-sign-keys
          readOnly: true
          mountPath: "/grr/exe/sign/keys"
      volumes:
      - name: grr-frontend-config
        secret:
          secretName: sec-grr-server-local
          items:
          - key: server.local.yaml
            path: server.local.yaml
      - name: grr-exe-sign-keys
        secret:
          secretName: sec-grr-executable-signing-keys
