apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timesketch-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/component: redis
    {{- include "timesketch.selectorLabels" . | nindent 4 }}