apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timesketch-worker-metrics
  labels:
    {{- include "timesketch.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: worker
    {{- include "timesketch.selectorLabels" . | nindent 4 }}