apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "turbinia.fullname" . }}-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: api
    {{- include "turbinia.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "turbinia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Restart pod if values.yaml parameters that affect the config were changed
        checksum/config: {{  include (print $.Template.BasePath "/init-configmap.yaml") . | sha256sum }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/scrape: "true"
        {{- end }}
      labels:
        app.kubernetes.io/component: api
        {{- include "turbinia.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "turbinia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      initContainers:
      {{- include "turbinia.initContainer" . | nindent 8 }} 
      containers:
        - name: api
          securityContext:
              {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          livenessProbe:
            exec:
              command: ['sh', '-c', "ps aux | grep api_server | grep -v grep"]
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /var/log
              name: logs
            - mountPath: /mnt/turbiniavolume
              name: turbiniavolume
            - mountPath: /etc/turbinia
              name: turbinia-configs
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
            {{- end }}
            - containerPort: 8000
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: turbiniavolume
          persistentVolumeClaim:
            claimName: {{ include "turbinia.pvc.name"  . }}
            readOnly: false
        - name: logs
          emptyDir: {}
        - name: init-turbinia
          configMap:
            name: {{ include "turbinia.fullname" . }}-init-configmap
            defaultMode: 0777
        - name: turbinia-configs
          emptyDir: {}
        - name: user-configs
          configMap:
            name: {{ include "turbinia.configmap" . }}
            optional: true
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}