{{- if .Values.oauth2proxy.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "turbinia.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
stringData:
  turbinia-secret: |
    {
      installed:
        {
            "client_id": {{ .Values.oauth2proxy.configuration.clientID | quote }},
            "client_secret": {{ .Values.oauth2proxy.configuration.clientSecret | quote }},
            "redirect_uris": [{{ .Values.oauth2proxy.configuration.redirectUrl | quote }}],
            "project_id": {{ .Values.gcp.projectID | quote }},
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
        }
    }
{{- end }}