apiVersion: v1
kind: Secret
metadata:
  name: {{ template "turbinia.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
stringData:
  {{- if .Values.oauth2proxy.enabled }}
  dftimewolf-secret: |
    {
      installed:
        {
            "client_id": "<NATIVE_CLIENT_ID>",
            "client_secret": "<NATIVE_CLIENT_SECRET>",
            "redirect_uris": [ "<https://<DOMAIN>.com/oauth2/callback>" ],
            "project_id": "<GCP_PROJECT_ID>",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
        }
    }
  {{- end }}
  turbinia-secret: |
    {
        "default": {
            "description": "This file is used by turbinia-client to determine the location of the API server and if authentication will be used. These options should match your Turbinia deployment.",
            "comments": "By default, the credentials and client secrets files are located in the user's home directory.",
            "API_SERVER_ADDRESS": "http://localhost",
            "API_SERVER_PORT": 8000,
            "API_AUTHENTICATION_ENABLED": false,
            "CLIENT_SECRETS_FILENAME": ".client_secrets.json",
            "CREDENTIALS_FILENAME": ".credentials_default.json"
        }
    }