apiVersion: v1
kind: Secret
metadata:
  name: {{ template "turbinia.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "turbinia.labels" . | nindent 4 }}
stringData:
  {{- if and .Values.oauth2proxy.enabled .Values.oauth2proxy.configuration.existingSecret }}
  dftimewolf-secret: |
    {
      installed:
        {
            "client_id": "{{ index (lookup "v1" "Secret" .Release.Namespace .Values.oauth2proxy.configuration.existingSecret).data "client-id-native" | b64dec }}",
            "client_secret": "",
            "redirect_uris": [ "https://{{ .Values.ingress.host }}.com/oauth2/callback" ],
            "project_id": "{{ .Values.gcp.projectID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
        }
    }
  {{- end }}
  turbinia-secret: |
    {
        "default": {
            "description": "This file is used by turbinia-client to determine the location of the API server and if authentication will be used. These options should match your Turbinia deployment.",
            "comments": "By default, the credentials and client secrets files are located in the user's home directory.",
            "API_SERVER_ADDRESS": "http://localhost",
            "API_SERVER_PORT": 8000,
            "API_AUTHENTICATION_ENABLED": false,
            "CLIENT_SECRETS_FILENAME": ".client_secrets.json",
            "CREDENTIALS_FILENAME": ".credentials_default.json"
        }
    }